# Generated by Django 4.2.5 on 2023-09-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='Unsubscribed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
